name: dma_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - libexpat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.10.19
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - argparse-addons==0.12.0
      - asammdf==7.4.2
      - attdict==1.0.3
      - attrs==25.4.0
      - beautifulsoup4==4.14.3
      - bitstruct==8.21.0
      - bs4==0.0.2
      - canmatrix==1.2
      - cantools==41.0.2
      - certifi==2026.1.4
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - construct==2.10.70
      - crccheck==1.3.1
      - decorator==5.2.1
      - diskcache==5.6.3
      - dnspython==2.8.0
      - fxpmath==0.4.9
      - geographiclib==2.1
      - geopy==2.4.1
      - greenlet==3.3.0
      - h5py==3.15.1
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - isal==1.8.0
      - isodate==0.7.2
      - joblib==1.5.3
      - llvmlite==0.46.0
      - lmdb==1.7.5
      - lockfile==0.12.2
      - lxml==6.0.2
      - lz4==4.4.5
      - macaddress==2.0.2
      - mdf-iter==2.1.1
      - more-itertools==10.8.0
      - moviepy==2.2.1
      - numba==0.63.1
      - numexpr==2.14.1
      - numpy==1.26.4
      - packaging==26.0
      - pandas==2.3.3
      - pillow==11.3.0
      - proglog==0.1.12
      - psac==2.6.55
      - pyftdi==0.13.4
      - pylibftdi==0.23.0
      - pymongo==4.16.0
      - pyrfc3339==2.1.0
      - pyserial==3.5
      - python-can==4.6.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyusb==1.3.1
      - pyyaml==6.0.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - retry2==0.9.5
      - rx==3.2.0
      - sbp==6.3.2
      - scipy==1.15.3
      - semver==3.0.4
      - six==1.17.0
      - soupsieve==2.8.3
      - sqlalchemy==2.0.46
      - termcolor==3.3.0
      - textparser==0.24.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.3
      - wrapt==1.17.3
      - xlsxwriter==3.2.9
prefix: C:\Users\thho0g\AppData\Local\anaconda3\envs\dma_env
